services:
  sample:
    image: sample
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sample-postgresql:5432/sample
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://sample-postgresql:5432/sample
      - JHIPSTER_SLEEP=30
    ports:
      - '8080:8080'
  sample-postgresql:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=sample
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
